types:
  - 'path'
  - 'point'
  - 'object'
  - 'area'

markers:
  - id: 0
    name: 'Power Tower'
    icon: 'powerTower'
    color: 'blue'
  - id: 1
    name: 'Wind Generator'
    icon: 'windGenerator'
    color: 'red'
  - id: 2
    name: 'Solar Panel'
    icon: 'solarPanel'
    color: 'green'
  - id: 3
    name: 'Default'
    icon: 'default'
    color: 'yellow'

# if dont have name is not modify
missionTypes:
  - id: 0
    name: 'Inspeccion de linea'
    type: 'path-object'
    case: 0 # planning
    description: 'select towers to create a path'
    data:
      devices:
        id:
          type: 'number'
          name: 'Device'
          default: 0
        category:
          type:
            [
              'dji_M210_noetic',
              'dji_M210_melodic',
              'dji_M210_noetic_rtk',
              'dji_M21_melodic_rtk',
              'dji_M210_noetic_rtk',
              'dji_M300',
              'dji_M300_rtk',
              'px4',
            ]
      settings:
        base:
          type: 'array'
          default: []
        inspection_speed:
          type: 'number'
          name: 'Inspection Speed'
          default: 7
        navigation_speed:
          type: 'number'
          name: 'Navigation speed'
          default: 15
        vertical_offset:
          type: 'number'
          name: 'Vertical offset'
          default: 10
        horizontal_offset:
          type: 'number'
          name: 'Horizontal offset'
          default: 10
        tower_height:
          type: 'number'
          name: 'Tower height'
          default: 10
        security_height:
          type: 'number'
          name: 'Segurity height'
          default: 10
  - id: 1
    name: 'inspeccion de torre'
    type: 'object'
    description: 'select towers '
    case: 1
    data:
      devices:
        id:
          type: 'number'
          name: 'Device'
          default: 0
        category:
          type:
            [
              'dji_M210_noetic',
              'dji_M210_melodic',
              'dji_M210_noetic_rtk',
              'dji_M21_melodic_rtk',
              'dji_M210_noetic_rtk',
              'dji_M300',
              'dji_M300_rtk',
            ]
      settings:
        base:
          type: 'array'
          default: []
        inspection_speed:
          type: 'number'
          name: 'Inspection Speed'
          default: 7
        navigation_speed:
          type: 'number'
          name: 'Navigation speed'
          default: 15
        vertical_offset:
          type: 'number'
          name: 'Vertical offset'
          default: 15
        horizontal_offset:
          type: 'number'
          name: 'Horizontal offset'
          default: 10
        tower_height:
          type: 'number'
          name: 'Tower height'
          default: 12
        security_height:
          type: 'number'
          name: 'Segurity height'
          default: 10
        orbital_points:
          type: 'number'
          name: 'Points in circle'
          default: 5

  - id: 2
    name: 'inspeccion de lidar'
    description: 'select towers to create a path'
    type: 'path-object'
    case: 2
    data:
      devices:
        id:
          type: 'number'
          name: 'Device'
          default: 0
        category:
          type: ['dji_M600']
      settings:
        base:
          type: 'array'
          default: []
        inspection_speed:
          type: 'number'
          name: 'Inspection Speed'
          default: 7
        navigation_speed:
          type: 'number'
          name: 'Navigation speed'
          default: 15
        vertical_offset:
          type: 'number'
          name: 'Vertical offset'
          default: 10
        horizontal_offset:
          type: 'number'
          name: 'Horizontal offset'
          default: 10
        tower_height:
          type: 'number'
          name: 'Tower height'
          default: 10
        security_height:
          type: 'number'
          name: 'Segurity height'
          default: 10

  - id: 3
    name: 'inspeccion de vegetacion'
    description: 'select empty in a map to inspection '
    type: 'point'
    case: 1
    data:
      devices:
        id:
          type: 'number'
          name: 'Device'
          default: 0
        category:
          type:
            [
              'dji_M210_noetic',
              'dji_M210_melodic',
              'dji_M210_noetic_rtk',
              'dji_M21_melodic_rtk',
              'dji_M210_noetic_rtk',
              'dji_M300',
              'dji_M300_rtk',
            ]
          default: ''
      settings:
        base:
          type: 'array'
          default: []
        inspection_speed:
          type: 'number'
          name: 'Inspection Speed'
          default: 7
        navigation_speed:
          type: 'number'
          name: 'Navigation speed'
          default: 15
        vertical_offset:
          type: 'number'
          name: 'Vertical offset'
          default: 25
        horizontal_offset:
          type: 'number'
          name: 'Horizontal offset'
          default: 50
        tower_height:
          default: 0
        security_height:
          type: 'number'
          name: 'Segurity height'
          default: 20
        orbital_points:
          type: 'number'
          name: 'points in circle'
          default: 5
        takeoff_height:
          type: 'number'
          default: 5
