init:
  - name: 'uav_2'
    category: 'dji_M210_noetic'
    ip: '10.42.0.43'
    user: 'ubuntu'
    pwd: 'ubuntu'
    camera:
      - type: 'WebRTC'
        source: 'main'

  - name: 'uav_3'
    category: 'px4'
    ip: '10.42.0.52'
    user: 'rock'
    pwd: 'rock'
    camera:
      - type: 'WebRTC'
        source: 'video0'

  - name: 'uav_14'
    category: 'dji_M300'
    ip: '10.42.0.51'
    user: 'nvidia'
    pwd: 'nvidia'
    camera:
      - type: 'WebRTC'
        source: 'main'

  - name: 'uav_15'
    category: 'dji_M300'
    ip: '10.42.0.45'
    user: 'khadas'
    pwd: 'khadas'
    camera:
      - type: 'WebRTC'
        source: 'main_resize'
