init:
  - name: 'uav_1'
    category: 'dji_M210_melodic'
    ip: '10.42.0.99'
    user: 'user'
    pwd: 'password'
    camera:
      - type: 'WebRTC'
        source: 'main'

  - name: 'uav_2'
    category: 'dji_M210_noetic'
    ip: '10.42.0.43'
    user: 'user'
    pwd: 'password'
    camera:
      - type: 'WebRTC'
        source: 'main'

  - name: 'uav_3'
    category: 'px4'
    ip: '10.42.0.52'
    camera:
      - type: 'WebRTC'
        source: 'video0'

  - name: 'uav_14'
    category: 'dji_M300'
    ip: '10.42.0.51'
    user: 'nvidia'
    pwd: 'nvidia'
    camera:
      - type: 'WebRTC'
        source: 'main_resize'

  - name: 'uav_15'
    category: 'dji_M300'
    ip: '10.42.0.45'
    user: 'khadas'
    pwd: 'khadas'
    camera:
      - type: 'WebRTC'
        source: 'main_resize'

  - name: 'uav_17'
    category: 'dji_M600'
    ip: '10.42.0.101'
    user: 'nvidia'
    pwd: 'nvidia'
    camera:
      - type: 'WebRTC'
        source: 'main_resize'

  - name: 'uav_100'
    category: 'catec'
    ip: '10.0.3.5'
    camera:
      - type: 'WebRTC_env'
        source: 'cam0'
      - type: 'WebRTC_env'
        source: 'cam1'
      - type: 'WebRTC_env'
        source: 'cam2'
      - type: 'WebRTC_env'
        source: 'cam3'

  - name: 'uav_20'
    category: 'fuvex'
    ip: '10.42.0.101'
    camera: []

  - name: 'uav0'
    category: 'px4'
    ip: '10.42.0.52'
    camera:
      - type: 'WebRTC'
        source: 'video0'

  - name: 'uav1'
    category: 'px4'
    ip: '10.42.0.52'
    camera:
      - type: 'WebRTC'
        source: 'video0'

  - name: 'uav2'
    category: 'px4'
    ip: '10.42.0.52'
    camera:
      - type: 'WebRTC'
        source: 'video0'
