type: waypoint
waypoint:
  - latitude: 37.19356003
    longitude: -6.702515
    altitude: 5
  - latitude: 37.19356003
    longitude: -6.702515
    altitude: 20
  - latitude: 37.192851763654815
    longitude: -6.70166921964713
    altitude: 17.65224457
  - latitude: 37.19286597
    longitude: -6.7015599
    altitude: 17.65224457
  - latitude: 37.19276068
    longitude: -6.70157432
    altitude: 17.65224457
  - latitude: 37.19271718
    longitude: -6.70145361
    altitude: 17.65224457
  - latitude: 37.19279558
    longitude: -6.70136459
    altitude: 17.65224457
  - latitude: 37.19300897180187
    longitude: -6.701423229784837
    altitude: 17.65224457
  - latitude: 37.19288753
    longitude: -6.70143029
    altitude: 17.65224457
  - latitude: 37.19356003
    longitude: -6.702515
    altitude: 20
  - latitude: 37.19356003
    longitude: -6.702515
    altitude: 5
radius: 0
maxVel: 10
idleVel: 7
yaw:
  data:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
speed:
  data:
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
    - 7
gimbalPitch:
  data:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
yawMode: 2
traceMode: 0
gimbalPitchMode: 0
finishAction: 2
commandList:
  data:
    - 5
    - 0
    - 0
    - 4
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 5
    - 0
    - 4
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 5
    - 0
    - 4
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 5
    - 0
    - 1
    - 4
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 5
    - 0
    - 1
    - 4
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 5
    - 0
    - 1
    - 4
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 5
    - 0
    - 1
    - 4
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 5
    - 0
    - 1
    - 4
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 5
    - 0
    - 4
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 5
    - 0
    - 4
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 5
    - 0
    - 0
    - 4
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
commandParameter:
  data:
    - -45
    - 0
    - 0
    - 130.86101182021565
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - -45
    - 0
    - 130.86101182021565
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - -45
    - 0
    - 130.86101182021565
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - -45
    - 0
    - 0
    - 94.86101181920665
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - -45
    - 0
    - 0
    - 22.86101182052933
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - -45
    - 0
    - 0
    - -49.138988178545254
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - -45
    - 0
    - 0
    - -121.13898817951834
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - -45
    - 0
    - 0
    - 166.8610118210563
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - -45
    - 0
    - -53.61536282238943
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - -45
    - 0
    - -53.61536282238943
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - -45
    - 0
    - 0
    - -53.61536282238943
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
