types:
  - 'path'
  - 'point'
  - 'object'
  - 'area'

# if dont have name is not modify
missionTypes:
  - id: 0
    name: 'Inspeccion de linea'
    type: 'path-object'
    case: 0 # planning
    description: 'select towers to create a path'
    data:
      devices:
        id:
          type: 'number'
          name: 'Device'
          default: 0
        category:
          type: ''
      settings:
        base:
          type: 'array'
          default: []
        inspection_speed:
          type: 'number'
          name: 'Inspection Speed'
          default: 7
        navigation_speed:
          type: 'number'
          name: 'Navigation speed'
          default: 15
        vertical_offset:
          type: 'number'
          name: 'Vertical offset'
          default: 10
        horizontal_offset:
          type: 'number'
          name: 'Horizontal offset'
          default: 10
        tower_height:
          type: 'number'
          name: 'Tower height'
          default: 10
        security_height:
          type: 'number'
          name: 'Segurity height'
          default: 10
  - id: 1
    name: 'inspeccion de torre'
    type: 'object'
    description: 'select towers '
    case: 1
    data:
      devices:
        id:
          type: 'number'
          name: 'Device'
          default: 0
        category:
          type: ''
      settings:
        base:
          type: 'array'
          default: []
        inspection_speed:
          type: 'number'
          name: 'Inspection Speed'
          default: 7
        navigation_speed:
          type: 'number'
          name: 'Navigation speed'
          default: 15
        vertical_offset:
          type: 'number'
          name: 'Vertical offset'
          default: 15
        horizontal_offset:
          type: 'number'
          name: 'Horizontal offset'
          default: 10
        tower_height:
          type: 'number'
          name: 'Tower height'
          default: 12
        security_height:
          type: 'number'
          name: 'Segurity height'
          default: 10
        orbital_points:
          type: 'number'
          name: 'Points in circle'
          default: 5

  - id: 2
    name: 'inspeccion de lidar'
    description: 'select towers to create a path'
    type: 'path-object'
    case: 2
    data:
      devices:
        id:
          type: 'number'
          name: 'Device'
          default: 0
        category:
          type: ''
      settings:
        base:
          type: 'array'
          default: []
        inspection_speed:
          type: 'number'
          name: 'Inspection Speed'
          default: 7
        navigation_speed:
          type: 'number'
          name: 'Navigation speed'
          default: 15
        vertical_offset:
          type: 'number'
          name: 'Vertical offset'
          default: 10
        horizontal_offset:
          type: 'number'
          name: 'Horizontal offset'
          default: 10
        tower_height:
          type: 'number'
          name: 'Tower height'
          default: 10
        security_height:
          type: 'number'
          name: 'Segurity height'
          default: 10

  - id: 3
    name: 'inspeccion de vegetacion'
    description: 'select empty in a map to inspection '
    type: 'point'
    case: 1
    data:
      devices:
        id:
          type: 'number'
          name: 'Device'
          default: 0
        category:
          type: ''
          default: ''
      settings:
        base:
          type: 'array'
          default: []
        inspection_speed:
          type: 'number'
          name: 'Inspection Speed'
          default: 7
        navigation_speed:
          type: 'number'
          name: 'Navigation speed'
          default: 15
        vertical_offset:
          type: 'number'
          name: 'Vertical offset'
          default: 20
        horizontal_offset:
          type: 'number'
          name: 'Horizontal offset'
          default: 15
        tower_height:
          default: 0
        security_height:
          type: 'number'
          name: 'Segurity height'
          default: 10
        orbital_points:
          type: 'number'
          name: 'points in circle'
          default: 5
        takeoff_height:
          type: 'number'
          default: 5
