id: 69535407
objetivo:
  id: 0
  name: Inspeccion de linea
  type: path-object
  case: 0
  description: select towers to create a path
loc: []
meteo: []
bases:
  - devices:
      id: 3
    settings:
      base: []
      inspection_speed: 7
      navigation_speed: 15
      vertical_offset: 10
      horizontal_offset: 10
      tower_height: 10
      security_height: 10
settings:
  devices:
    id:
      type: number
      name: Device
      default: 0
    category:
      type: ''
  settings:
    base:
      type: array
      default: []
    inspection_speed:
      type: number
      name: Inspection Speed
      default: 7
    navigation_speed:
      type: number
      name: Navigation speed
      default: 15
    vertical_offset:
      type: number
      name: Vertical offset
      default: 10
    horizontal_offset:
      type: number
      name: Horizontal offset
      default: 10
    tower_height:
      type: number
      name: Tower height
      default: 10
    security_height:
      type: number
      name: Segurity height
      default: 10
markersbase:
  - latitude: 37.41019548120744
    longitude: -6.002340287800763
elements:
  - type: powerTower
    name: Elements
    linea: true
    items:
      - latitude: 37.410240824022154
        longitude: -6.00228464818602
      - latitude: 37.41028846264658
        longitude: -6.002229008572243
      - latitude: 37.410316012679914
        longitude: -6.0021748141426485
